Shultz 13
AVanDeBrook/citation-graph pull request #31
Opened 2021-03-19 19:59 UTC by spoofaloof

Luis helped pizzazzz this branch out

2021-03-19 20:53 UTC, AVanDeBrook requested changes
All pages:
  * Add `<body>` tags

`contact.html`:
  * Add `<a href="mailto:<email>"` to emails

2021-03-19 21:04 UTC, AVanDeBrook commented
I'm also gonna have to reorganize the file structure when it gets merged with the server so that it can find all the referenced resources.

2021-03-20 01:24 UTC, AVanDeBrook approved these changes

2021-03-22 12:39 UTC, corrinadelgreco approved these changes

2021-03-22 17:26 UTC, samanthacombs approved these changes

2021-03-22 17:26 UTC, merged